kafka:
  brokers:
    - redpanda:9092

server:
  listenPort: 8080

# Отображать все внутренние топики Redpanda
kafka:
  brokers:
    - redpanda:9092
  schemaRegistry:
    enabled: true
    urls:
      - "http://redpanda:8081"
